dist: trusty
language: clojure
lein: 2.8.1
before_script:
   - ./scripts/run_swapi.sh & 
   - sleep 60
script: lein midje
jdk:
  - oraclejdk8
  - openjdk8
  - oraclejdk9
services:
  - mongod
addons:
  firefox: "45.4.0esr"
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver