log-level: debug

webserver:
  security:
      anti-forgery: false
      ssl-redirect: false
  session:
      cookie-attrs:
        # this number is the time in seconds until the session expires
        max-age: 600
        # change this to true for https only on production
        secure: false  

just-auth:
  email-config: "email-conf.yaml"
  mongo-config:
    host: localhost
    port: 27017
    db: social-wallet
  throttling:
    criteria: !!set {!keyword email: null, !keyword ip-address: null}
    type: !keyword block
    time-window-secs: 3600
    threshold: 1000

swapi:
  base-url: "http://localhost:3000/wallet/v1"
  apikey-file: "../social-wallet-api/apikey.yaml"
  apikey-name: "device-id"